import type { Course } from "./types"

export const courses: Course[] = [
  {
    id: "ai-income-systems",
    title: "AI Income Systems",
    description: "The flagship course to build AI-powered income streams from scratch.",
    longDescription:
      "Master the art of leveraging artificial intelligence to create sustainable income streams. This comprehensive course covers everything from identifying opportunities to building and scaling AI-powered businesses. You'll learn proven frameworks used by successful entrepreneurs to generate consistent revenue.",
    price: 497,
    image: "/courses/ai-income-systems.jpg",
    features: [
      "12+ hours of video content",
      "Downloadable templates and tools",
      "Private community access",
      "Weekly live Q&A sessions",
      "Lifetime updates",
    ],
    category: "Featured",
    isFeatured: true,
    createdAt: new Date(),
    lessons: [
      {
        id: "ais-1",
        title: "Introduction to AI Income",
        description: "Understanding the landscape of AI-powered business opportunities.",
        content: "Welcome to AI Income Systems...",
        duration: 45,
        order: 1,
      },
      {
        id: "ais-2",
        title: "Finding Your AI Niche",
        description: "How to identify profitable niches for AI services.",
        content: "In this lesson, we'll explore...",
        duration: 60,
        order: 2,
      },
      {
        id: "ais-3",
        title: "Building Your First AI Tool",
        description: "Step-by-step guide to creating your first AI product.",
        content: "Now that you've identified...",
        duration: 75,
        order: 3,
      },
      {
        id: "ais-4",
        title: "Marketing AI Services",
        description: "How to market and sell your AI solutions.",
        content: "Marketing AI services requires...",
        duration: 55,
        order: 4,
      },
      {
        id: "ais-5",
        title: "Scaling Your AI Business",
        description: "Strategies for growing and automating your income.",
        content: "Once you have traction...",
        duration: 65,
        order: 5,
      },
    ],
  },
  {
    id: "ai-local-business",
    title: "AI for Local Businesses",
    description: "Learn to sell AI services to real businesses in your area.",
    longDescription:
      "Discover how to approach local businesses and provide them with AI solutions that solve real problems. From lead generation to customer service automation, you'll learn how to package and sell AI services to businesses that need them most.",
    price: 297,
    image: "/courses/ai-local-business.jpg",
    features: [
      "8+ hours of video content",
      "Sales scripts and templates",
      "Client proposal templates",
      "Case study library",
      "30-day action plan",
    ],
    category: "Business",
    isFeatured: true,
    createdAt: new Date(),
    lessons: [
      {
        id: "alb-1",
        title: "The Local Business Opportunity",
        description: "Why local businesses need AI now more than ever.",
        content: "Local businesses are...",
        duration: 40,
        order: 1,
      },
      {
        id: "alb-2",
        title: "AI Solutions That Sell",
        description: "The most in-demand AI services for local businesses.",
        content: "In this module...",
        duration: 55,
        order: 2,
      },
      {
        id: "alb-3",
        title: "Finding and Approaching Clients",
        description: "How to identify and reach out to potential clients.",
        content: "Finding clients is...",
        duration: 50,
        order: 3,
      },
      {
        id: "alb-4",
        title: "Closing the Deal",
        description: "Sales techniques that work for AI services.",
        content: "Closing deals for AI...",
        duration: 45,
        order: 4,
      },
    ],
  },
  {
    id: "no-code-ai-saas",
    title: "No-Code AI Micro-SaaS",
    description: "Build and launch a small AI subscription product without coding.",
    longDescription:
      "Learn how to create a profitable micro-SaaS product using no-code tools and AI. This course walks you through ideation, building, launching, and monetizing a subscription-based AI product without writing a single line of code.",
    price: 347,
    image: "/courses/no-code-saas.jpg",
    features: [
      "10+ hours of video content",
      "No-code tool tutorials",
      "Launch checklist",
      "Pricing strategy guide",
      "Marketing templates",
    ],
    category: "Development",
    isFeatured: true,
    createdAt: new Date(),
    lessons: [
      {
        id: "ncs-1",
        title: "What is Micro-SaaS?",
        description: "Understanding the micro-SaaS business model.",
        content: "Micro-SaaS refers to...",
        duration: 35,
        order: 1,
      },
      {
        id: "ncs-2",
        title: "Finding Your Product Idea",
        description: "How to validate and choose your SaaS idea.",
        content: "Finding the right idea...",
        duration: 50,
        order: 2,
      },
      {
        id: "ncs-3",
        title: "Building with No-Code",
        description: "Step-by-step building using no-code platforms.",
        content: "Building your product...",
        duration: 90,
        order: 3,
      },
      {
        id: "ncs-4",
        title: "Launching Your SaaS",
        description: "How to launch and get your first customers.",
        content: "Launch day is...",
        duration: 55,
        order: 4,
      },
    ],
  },
  {
    id: "freelancing-with-ai",
    title: "Freelancing with AI",
    description: "Use AI to deliver freelance services with no prior experience.",
    longDescription:
      "Start freelancing immediately by leveraging AI tools to deliver professional services. Learn how to use AI for writing, design, development, and more to build a successful freelance career from day one.",
    price: 197,
    image: "/courses/freelancing-ai.jpg",
    features: [
      "6+ hours of video content",
      "AI tool recommendations",
      "Freelance platform guides",
      "Portfolio templates",
      "Client management tips",
    ],
    category: "Freelancing",
    isFeatured: false,
    createdAt: new Date(),
    lessons: [
      {
        id: "fwa-1",
        title: "AI-Powered Freelancing",
        description: "How AI is changing the freelance landscape.",
        content: "The freelance economy...",
        duration: 30,
        order: 1,
      },
      {
        id: "fwa-2",
        title: "Choosing Your Services",
        description: "Which services to offer with AI assistance.",
        content: "Selecting the right...",
        duration: 45,
        order: 2,
      },
      {
        id: "fwa-3",
        title: "Setting Up Your Business",
        description: "Creating profiles and establishing your presence.",
        content: "Setting up your...",
        duration: 40,
        order: 3,
      },
    ],
  },
  {
    id: "personal-finance-ai",
    title: "Personal Finance for the AI Era",
    description: "Managing income, taxes, and stability with AI-driven work.",
    longDescription:
      "Navigate the financial complexities of AI-driven income. Learn about tax strategies, income diversification, investment approaches, and building financial stability in the new economy.",
    price: 147,
    image: "/courses/personal-finance.jpg",
    features: [
      "5+ hours of video content",
      "Tax planning worksheets",
      "Budget templates",
      "Investment frameworks",
      "Income tracking tools",
    ],
    category: "Finance",
    isFeatured: false,
    createdAt: new Date(),
    lessons: [
      {
        id: "pfa-1",
        title: "AI Income Fundamentals",
        description: "Understanding income patterns in AI work.",
        content: "Income from AI...",
        duration: 35,
        order: 1,
      },
      {
        id: "pfa-2",
        title: "Tax Strategies",
        description: "How to handle taxes for multiple income streams.",
        content: "Tax planning is...",
        duration: 50,
        order: 2,
      },
      {
        id: "pfa-3",
        title: "Building Stability",
        description: "Creating financial security with variable income.",
        content: "Financial stability...",
        duration: 45,
        order: 3,
      },
    ],
  },
  {
    id: "idea-to-dollar",
    title: "From Idea to First Dollar",
    description: "Make your first online dollar fast with proven strategies.",
    longDescription:
      "The fastest path to making money online. This action-oriented course focuses on quick wins and proven strategies to help you earn your first dollar online within days, not months.",
    price: 97,
    image: "/courses/first-dollar.jpg",
    features: [
      "4+ hours of video content",
      "Quick-start action plans",
      "Revenue ideas database",
      "Step-by-step guides",
      "Community support",
    ],
    category: "Beginner",
    isFeatured: false,
    createdAt: new Date(),
    lessons: [
      {
        id: "itd-1",
        title: "The Fastest Path to Income",
        description: "Mindset and strategies for quick results.",
        content: "Making your first...",
        duration: 25,
        order: 1,
      },
      {
        id: "itd-2",
        title: "Quick Win Strategies",
        description: "Proven methods to earn fast.",
        content: "These strategies have...",
        duration: 40,
        order: 2,
      },
      {
        id: "itd-3",
        title: "Taking Action",
        description: "Implementing what you've learned.",
        content: "Now it's time to...",
        duration: 30,
        order: 3,
      },
    ],
  },
]

export function getCourse(id: string): Course | undefined {
  return courses.find((course) => course.id === id)
}

export function getFeaturedCourses(): Course[] {
  return courses.filter((course) => course.isFeatured)
}
